apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "surf-screenshotter.fullname" . }}
  labels:
  {{- include "surf-screenshotter.labels" . | nindent 4 }}
data:
  data.txt: |
    {{- .Values.workerData | nindent 4 }}
  nginx-default.conf: |
    {{ .Files.Get .Values.nginxDefaultConf | nindent 4 }}
