apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "surf-screenshotter.fullname" . }}
  labels:
    {{- include "surf-screenshotter.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "surf-screenshotter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "surf-screenshotter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "surf-screenshotter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-www
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.wwwImage.name | quote }}
          imagePullPolicy: {{ .Values.wwwImage.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: configmap-nginx
              mountPath: /etc/nginx/conf.d
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "surf-screenshotter.fullname" . }}
        - name: configmap-nginx
          configMap:
            name: {{ include "surf-screenshotter.fullname" . }}
            items:
              - key: nginx-default.conf
                path: default.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
