apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "surf-screenshotter.fullname" . }}
  labels:
  {{- include "surf-screenshotter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
