apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "surf-screenshot.fullname" . }}
  labels:
  {{- include "surf-screenshot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
